import { prisma } from "@/lib/prisma";
import { formatPrice } from "@/lib/utils";
import { updateOrder } from "./actions";
import { measurementLines, parseMeasurements } from "@/lib/measurements";
import CopyMeasurementsButton from "@/components/admin/CopyMeasurementsButton";

export const dynamic = "force-dynamic";
const statuses = ["pending", "confirmed", "shipped", "delivered", "cancelled"];

export default async function AdminOrdersPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const q = (await searchParams).q?.trim() ?? "";
  const orders = await prisma.order.findMany({ where: q ? { OR: [{ orderCode: { contains: q.toUpperCase() } }, { name: { contains: q } }, { email: { contains: q } }, { phone: { contains: q } }] } : undefined, include: { items: { include: { product: true } } }, orderBy: { createdAt: "desc" } });
  return <div><div className="mb-8"><h1 className="font-heading text-[24px] font-medium">Orders</h1><p className="mt-1 font-body text-[13px] text-muted">Manage WhatsApp customer orders</p></div>
    <form className="mb-6 flex max-w-xl flex-wrap gap-3"><input name="q" defaultValue={q} placeholder="Search order ID, customer, email or phone" className="min-w-0 basis-full rounded-full border border-line px-5 py-3 font-body text-[13px] outline-none focus:border-primary sm:flex-1 sm:basis-auto" /><button className="rounded-full bg-black px-6 py-3 font-body text-[11px] uppercase tracking-[1px] text-white">Search</button>{q && <a href="/admin/orders" className="self-center font-body text-[11px] text-muted">Clear</a>}</form>
    {orders.length === 0 ? <div className="border border-dashed border-line py-16 text-center font-body text-[13px] text-muted">{q ? `No orders found for “${q}”.` : "No orders yet."}</div> : <div className="space-y-4">{orders.map((order) => <article key={order.id} className="min-w-0 border border-line p-4 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:flex-wrap sm:justify-between"><div className="min-w-0"><p className="break-all font-heading text-[15px]">#{order.orderCode ?? order.id}</p><p className="break-words font-body text-[13px] text-muted">{order.name} · {order.phone || order.email}</p><p className="mt-1 break-words font-body text-[12px] text-muted">{order.address}, {order.city}, {order.state} {order.zip}</p></div><div className="sm:text-right"><p className="font-heading text-[16px] text-gold">{formatPrice(order.total)}</p><p className="font-body text-[11px] text-muted">{order.createdAt.toLocaleString("en-NG")}</p></div></div>
      <div className="mt-4 border-t border-line pt-4 font-body text-[12px] text-muted">{order.items.map((item) => <p key={item.id}>{item.product.name} · {item.size} · {item.color} × {item.quantity} — {formatPrice(item.price * item.quantity)}</p>)}</div>
      {order.gender && <section className="mt-4 rounded-xl bg-[#F7F2E8] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-body text-[11px] font-semibold uppercase tracking-[2px] text-black">Customer Measurements</h3><p className="mt-1 font-body text-[11px] text-muted">{order.gender} · {order.measurementUnit ?? "inches"} · Captured {order.measurementCapturedAt?.toLocaleString("en-NG") ?? "with order"}</p></div><CopyMeasurementsButton text={[`Gender: ${order.gender}`, `Measurement Unit: ${order.measurementUnit ?? "inches"}`, ...measurementLines(order.gender, parseMeasurements(order.measurementSnapshot), order.measurementUnit ?? "inches")].join("\n")} /></div><div className="mt-4 grid grid-cols-2 gap-x-6 gap-y-2 font-body text-[12px] text-muted md:grid-cols-3">{measurementLines(order.gender, parseMeasurements(order.measurementSnapshot), order.measurementUnit ?? "inches").map((line) => <p key={line}>{line}</p>)}</div></section>}
      <form action={updateOrder} className="mt-4 flex flex-col items-stretch gap-3 sm:flex-row sm:flex-wrap sm:items-end"><input type="hidden" name="id" value={order.id} /><label className="flex flex-col gap-1 font-body text-[11px] text-muted">Order status<select name="status" defaultValue={order.status} className="border border-line bg-white p-2">{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><label className="flex flex-col gap-1 font-body text-[11px] text-muted">Payment<select name="paymentStatus" defaultValue={order.paymentStatus} className="border border-line bg-white p-2"><option value="pending">pending</option><option value="paid">paid</option></select></label><button className="bg-black px-4 py-2 font-body text-[11px] uppercase tracking-[1px] text-white">Update</button></form>
    </article>)}</div>}
  </div>;
}
