import { prisma } from "@/lib/prisma";
import { formatPrice } from "@/lib/utils";
import { createDiscount, deleteDiscount, toggleDiscount } from "./actions";

export const dynamic = "force-dynamic";
export default async function AdminDiscountsPage() {
  const discounts = await prisma.discountCode.findMany({ orderBy: { createdAt: "desc" } });
  return <div><div className="mb-8"><h1 className="font-heading text-[24px] font-medium">Discount Codes</h1><p className="mt-1 font-body text-[13px] text-muted">Create and manage promotional codes</p></div>
    <form action={createDiscount} className="grid gap-4 border border-line p-4 sm:p-6 md:grid-cols-6"><input name="code" required placeholder="CODE" className="min-w-0 border-b border-black p-2 font-body text-[13px]" /><select name="type" className="min-w-0 border-b border-black bg-white p-2 font-body text-[13px]"><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select><input name="value" required type="number" min="1" placeholder="Value" className="min-w-0 border-b border-black p-2 font-body text-[13px]" /><input name="minOrder" type="number" min="0" placeholder="Minimum order" className="min-w-0 border-b border-black p-2 font-body text-[13px]" /><input name="usageLimit" type="number" min="1" placeholder="Usage limit" className="min-w-0 border-b border-black p-2 font-body text-[13px]" /><button className="cta-primary px-4">Add Code</button></form>
    <div className="mt-8 max-w-full overflow-x-auto border border-line"><table className="min-w-[720px] w-full text-left"><thead><tr className="border-b border-line bg-black/5">{["Code","Value","Minimum","Usage","Status","Actions"].map((x) => <th key={x} className="px-5 py-4 font-body text-[11px] uppercase tracking-[2px] text-muted">{x}</th>)}</tr></thead><tbody>{discounts.map((d) => <tr key={d.id} className="border-b border-line last:border-0"><td className="px-5 py-4 font-heading text-[14px]">{d.code}</td><td className="px-5 py-4 font-body text-[13px]">{d.type === "percentage" ? `${d.value}%` : formatPrice(d.value)}</td><td className="px-5 py-4 font-body text-[13px]">{d.minOrder ? formatPrice(d.minOrder) : "None"}</td><td className="px-5 py-4 font-body text-[13px]">{d.usedCount}/{d.usageLimit ?? "∞"}</td><td className="px-5 py-4 font-body text-[11px] uppercase text-primary">{d.active ? "Active" : "Inactive"}</td><td className="px-5 py-4"><div className="flex gap-3"><form action={toggleDiscount}><input type="hidden" name="id" value={d.id}/><button className="font-body text-[11px] uppercase text-primary">Toggle</button></form><form action={deleteDiscount}><input type="hidden" name="id" value={d.id}/><button className="font-body text-[11px] uppercase text-red-700">Delete</button></form></div></td></tr>)}</tbody></table></div>
  </div>;
}
